package ham.citybuildersim;

/**
 * The road network: what the city's buildings demand of it, what it can carry,
 * and what happens when the first number passes the second.
 *
 * WHY ROADS ARE A BUILDING
 *
 * A road is not obviously a building, and the first instinct is to model the
 * network as its own continuous quantity. It is modelled as a BuildingType
 * instead, and that choice buys the whole feature almost for free: ordering road
 * capacity goes through the construction sector, consumes materials and land,
 * takes months to finish, shows up in the construction queue, can be demolished,
 * and survives a save - all of it machinery that already exists and is already
 * tested. A parallel system would have had to reimplement every one of those and
 * would have been the only thing in the game that worked differently.
 *
 * The city pays for roads out of its own cash, like the power and water plants,
 * and the construction sector earns the revenue for building them. That is the
 * point of putting them through construction rather than conjuring them: public
 * works are a demand-side lever on a private industry, and now they visibly are.
 *
 * WHY THE RESPONSE CURVE IS NOT A STRAIGHT LINE
 *
 * Electricity and water are step functions in this game: the ratio is
 * production over consumption, so a city one unit short is a city 99% supplied.
 * That is right for a wire and wrong for a road.
 *
 * Traffic does not degrade linearly. A network runs at full speed until it is
 * near capacity and then falls over fairly suddenly, which is why a road that
 * carried yesterday's traffic fine can gridlock after one more office opens. So
 * the network here is free-flowing up to FREE_FLOW of capacity and degrades as
 * the inverse of how far past that it is pushed.
 *
 * And it has a floor. A gridlocked city still moves - people walk, deliveries
 * arrive late rather than never - so throughput bottoms out at MIN_THROUGHPUT
 * rather than going to zero the way an unpowered factory does. That makes
 * congestion a tax on growth rather than an instant death, which is the right
 * shape for something a player is meant to notice and then fix.
 */
public class InfrastructureManager {

    /**
     * The streets that already exist, before the city builds anything.
     *
     * Without this the first building in a brand new city would find a network
     * of capacity zero and gridlock instantly - the same turn-one wall the land
     * pass hit when the starting allocation was too small to fit a power plant.
     * A city starts with roads; what it does not start with is enough of them.
     */
    public static final double BASE_CAPACITY = 400;

    /** Up to this share of capacity, traffic moves freely. */
    public static final double FREE_FLOW = .9;

    /** However bad it gets, the city does not stop moving entirely. */
    public static final double MIN_THROUGHPUT = .35;

    /** Utilisation past which the network is worth warning about. */
    public static final double STRAINED = .85;

    private double capacity = BASE_CAPACITY;
    private double load;

    /* ------------------------------- inputs ------------------------------- */

    /**
     * @param builtCapacity what the road buildings standing in the city provide,
     *                      before the base network is added
     */
    public void setBuiltCapacity(double builtCapacity) {
        this.capacity = BASE_CAPACITY + Math.max(0, builtCapacity);
    }

    /** Total monthly trips generated by everything standing. */
    public void setLoad(double load) {
        this.load = Math.max(0, load);
    }

    /* ------------------------------- results ------------------------------- */

    public double getCapacity() { return capacity; }
    public double getLoad()     { return load; }

    /** Built capacity only - what the player actually paid for. */
    public double getBuiltCapacity() {
        return Math.max(0, capacity - BASE_CAPACITY);
    }

    /** Load over capacity. Above 1 the network is carrying more than it can. */
    public double getUtilisation() {
        return (capacity > 0) ? load / capacity : 0;
    }

    public double getSpareCapacity() {
        return Math.max(0, capacity - load);
    }

    /**
     * What fraction of its business the city can actually conduct.
     *
     * Applied the way energyRatio and waterRatio already are - as a multiplier
     * on retail sales, industrial output and the rate construction can build -
     * because those are exactly the three things that stop working when nothing
     * can get anywhere.
     */
    public double getThroughputRatio() {

        if (load <= 0 || capacity <= 0) return 1;

        double utilisation = getUtilisation();
        if (utilisation <= FREE_FLOW) return 1;

        // Past free flow, throughput is the inverse of how far over it is
        // pushed: 10% over free flow costs about 10%, twice over costs half.
        return Math.max(MIN_THROUGHPUT, FREE_FLOW / utilisation);
    }

    public boolean isCongested() {
        return getThroughputRatio() < 1;
    }

    /** True while there is still room, but not much. */
    public boolean isStrained() {
        return !isCongested() && getUtilisation() >= STRAINED;
    }

    /**
     * How much more the network could carry before traffic starts to slow.
     *
     * The number a player actually wants: not "how much capacity is unused" but
     * "how much more can I build before this hurts".
     */
    public double getHeadroom() {
        return Math.max(0, capacity * FREE_FLOW - load);
    }

    /** One line for the city panel. */
    public String getStatus() {
        if (load <= 0)      return "Clear";
        if (isCongested())  return "Congested";
        if (isStrained())   return "Busy";
        return "Clear";
    }

    public void reset() {
        capacity = BASE_CAPACITY;
        load = 0;
    }
}
